### ISSUE TITLE
Bad JS output

### ISSUE THREAD

**Issue by felixge** [weepy/kaffeine#26]
It seems like kaffeine adds a return statement to line 3 of this code:

```
CurlCommand.escapeConfigValue = function(argument) {
  argument += '';
  argument = argument.replace(/\\/g, '\\\\');
  argument = argument.replace(/"/g, '\\"');
  argument = argument.replace(/\n/g, '\\n');
  argument = argument.replace(/\t/g, '\\t');
  argument = argument.replace(/\r/g, '\\r');
  argument = argument.replace(/\v/g, '\\v');
  return '"'+argument+'"';
};
```

The error I'm getting is this:

```
/var/git/transloader.transload.it/api2/node_modules/transloadit/command/curl_command.js (compiled):101
  return argument = argument.replace(/\\/g, '\\\\');\n\
                                                    ^

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:399:25)
    at /usr/local/lib/node_modules/kaffeine/lib/index.js:94:12
    at Object..js (/var/git/transloader.transload.it/api2/node_modules/transloadit/transloadit.js:9:12)
    at Module.load (module.js:336:31)
    at Function._load (module.js:297:12)
    at require (module.js:348:19)
    at Object.<anonymous> (/var/git/transloader.transload.it/api2/node_modules/transloadit/assembly.js (compiled):10:19)
    at Module._compile (module.js:404:26)
    at /usr/local/lib/node_modules/kaffeine/lib/index.js:94:12
    at Object..js (/var/git/transloader.transload.it/api2/node_modules/transloadit/transloadit.js:9:12)
```

**Comment by weepy** [comment]
yeah - the implicit return code looks like it has a few holes in it - trying
to refix now.

btw - you know you can try kaffeine in the browser :
http://weepy.github.com/kaffeine/docs/try.html

it's quite useful for trying stuff out.

**Comment by weepy** [comment]
it looks like the tokenizer is having trouble with this line :  argument =
argument.replace(/\/g, '\\');
==> investigating.

**Comment by weepy** [comment]
i just pushed a fix for this

**Comment by weepy** [comment]
felix - can you let me know if this worked for you ? cheers

**Comment by felixge** [comment]
Sorry, I can't test right now because my macbook is broken and I only have a limited work environment. I'll let you know how my next Kaffeine adventure goes next week!

**Comment by weepy** [comment]
Cool. Have fun. I'm off to Turkey for 2 weeks. So I might not reply!
Btw I put up a new version with a class system.

Tapped on my fone

On 23 Apr 2011, at 09:30, felixge
reply@reply.github.com
wrote:

**Comment by adrusi** [comment]
it looks like its escaping the closing quotes and end of regexps before escaping their content so that it thinks the closing parens are part of the regexp.

**Comment by weepy** [comment]
closing
