### ISSUE TITLE
Horrible nodejs support

### ISSUE THREAD

**Issue by adrusi** [weepy/kaffeine#29]
I've made countless changes to the nodejs compiler and executor to get it to simply run and it now compiles wrong. When I compile this code with `$ kaffeine --compile`...

```
http.createServer (request, response) {
  // stuff
}
```

It compiles to:

```
http.createServer((request, response)(function() {
  // stuff
}));
```

and obviously doesn't work as expected. The same code compiles perfectly in the browser.

**Comment by adrusi** [comment]
nevermind, I got it working now, but it still shouldn't require the end user to modify the module for it to work

**Comment by weepy** [comment]
Terribly sorry. I've recently made a change to the compiler and not
updated the documentation. You need to use the coffee script style
arrow for functions now:

> http.createServer (request, response) -> {
>      // stuff
>    }

I really should update the documentation v soon.

Could you make a pull request for your changes ?

Tapped on my fone

On 14 May 2011, at 18:52, adrusi
reply@reply.github.com
wrote:

**Comment by adrusi** [comment]
I've tried everything, but I think I messed something up with the git repository and I can't push to my fork, I only made changes to bin/command.js. [Here's a gist with the changes](https://gist.github.com/1056962).

**Comment by weepy** [comment]
merged ...
