### ISSUE TITLE
Function syntax is ambiguous

### ISSUE THREAD

**Issue by adrusi** [weepy/kaffeine#39]
No, I don't mean with an object literal, that's covered in the docs, I mean with a function invocation.

Suppose I define this function:

```
fn = (a, b, c) {
  (f) {
    f(a, b, c)
  }
}
```

It's a higher-order function that returns a function that accepts a functions and executes it.

You might call it like this:

```
a = 1
b = 2
c = 3

fn(a, b, c)({
  # + #1 + #2
})
```

but you  might drop this second parens

```
fn(a, b, c) {
  # + #1 + #2
}
```

and then for whatever reason you might add a space after the function:

```
fn (a, b, c) {
  # + #1 + #2
}
```

which is ambiguous with calling `fn` if `fn` were defined as

```
fn = (f) {
  f(1, 2, 3)
}
```

I didn't encounter this in actual code, I just noticed it. You could solve it by doing what ruby does and not allowing a space between a function and the parens.

**Comment by weepy** [comment]
sorry for the super later reply - i only just noticed this.

... it also makes my brain hurt ^_^

**Comment by weepy** [comment]
well --- for reasons like this - I've actually changed the function syntax to be more similar to CoffeeScript, ie. with the arrow syntax. I need to update the docs !!!

**Comment by weepy** [comment]
closing
