### ISSUE TITLE
Async bug?

### ISSUE THREAD

**Issue by pheze** [weepy/kaffeine#42]
This:

```
sleep = { setTimeout #1, #0 }

for x in [1,2,3]
  sleep!(100)
  console.log(x)
```

Results in:

```
var sleep;

sleep = function() {
   return setTimeout(arguments[1], arguments[0]);
};

for (x in [ 1, 2, 3 ]) sleep(100, function() {});  

console.log(x);
```

Shouldn't the console.log be included in the sleep callback?

**Comment by weepy** [comment]
good catch ! not sure what's going on here

**Comment by amigrave** [comment]
Kaffeine is doing things right here !

You're writing coffeescript like syntax so it is harder to point out what's wrong.
Kaffeine does not uses whitespace indentation.

For kaffeine those three code blocks are the same :

```
for x in [1,2,3]
    sleep!(100)
    console.log(x)
```

```
for x in [1,2,3]
    sleep!(100)
console.log(x)
```

```
for x in [1,2,3] {
    sleep!(100)
}
console.log(x)
```

See ? you only have the sleep statement in the loop, as such, kaffeine has no statement to give to the async, so it uses an empty function.

What you really want is this:

```
sleep = { setTimeout #1, #0 }

for x in [1,2,3] {
  sleep!(100)
  console.log(x)
}
```

results to

```
var sleep; sleep = function() { return setTimeout(arguments[1], arguments[0]) }

for(x in [1,2,3]) {
  sleep(100, function() {
  console.log(x) })
}
```

**Comment by weepy** [comment]
yes of course ! -- Kaffeine is more like Javascript than CoffeeScript ^_^

closing for now.
