### ISSUE TITLE
is this project dead?

### ISSUE THREAD

**Issue by yjgaia** [weepy/kaffeine#50]
i like kaffeine's syntax.
is this project dead?

**Comment by weepy** [comment]
Thanks, though I'm no longer actively working on it.

**Comment by yjgaia** [comment]
Thanks to your reply.
but please fix the one bug for me.
I'm in trouble when make a framework using Kaffeine now.

self = {};
self.a = a = function() {};
-> code is ok, but 'a' is not generated to compiled-JS code. (like var a = func...);

I want to use Kaffeine for my framework UPPERCASE ( http://uppercase.io ).
I'm making UPPERCASE's sub project run with Kaffeine, UPPERKASE( https://github.com/BTNcafe/UPPERKASE ).

I LOVE Kaffeine's systax (Especially, syntax for async.)

p.s. sorry for my english ;(

**Comment by weepy** [comment]
can you try

a = self.a = function() { }

**Comment by weepy** [comment]
what is UPPERCASE.io ?

**Comment by yjgaia** [comment]
uppercase.io is full-stack framework like meteor.
i wanna use self.a = a = function() {}.
is it impossible? ㅜㅜ

**Comment by weepy** [comment]
i don't know I'm afaid, what's wrong with

a = self.a = .. ?

**Comment by yjgaia** [comment]
oh, it is not wrong. :)
just i want it.
I have often been so write source code.

https://github.com/BTNcafe/UPPERCASE-EXAMPLES/blob/master/WebPageExample/BROWSER/View.js

```
self.close = close = function(params) {
    div.remove();
};
```

**Comment by weepy** [comment]
damn - sorry im not going to have time to figure out what the problem is.
certainly quicker for you to write "close = self.close etc " ..

**Comment by yjgaia** [comment]
ok weepy, thanks.
and thank you so much for creating Kaffeine, too
