### ISSUE TITLE
Is there operator overloading

### ISSUE THREAD

**Issue by IdkGoodName** [weepy/kaffeine#54]
Is there operator overloading, or at least any plans making if not?

**Comment by weepy** [comment]
I’m not sure how it would work ? Any ideas ?

**Comment by CreatorVilius** [comment]
`something + something` would be converted to `something.add(something)`

**Comment by IdkGoodName** [comment]
```js
lorem + ipsum
```
Would be converted to
```js
lorem['+'](ipsum)
```
